- README.md
GitHub's markdown parser requires the code blocks themselves to be indented to the same level as the outer indentation to parse them correctly.
> Fix formatting of code in build instructions

- README.md
git has no command 'submodules' rather the instruction should be 'git submodule update --remote' . :smile:
> Small typo fix in Readme. submodules -> submodule .

- .gitmodules
- .travis.yml
- we don't doubly-build PRs coming from my own branch
- no need to use OPAM sandboxing in CI builds
- check npm dependencies too
- remove CodeMirror submodule in favor of npm
> [ci] [travis] Some tweaks to Travis

- coq-js/icoq.ml
- coq-js/icoq.mli
- coq-js/jscoq.js
- coq-js/jscoq_worker.ml
- coq-libjs/str.js
- package-lock.json
- package.json
- ui-js/coq-manager.js
I have completed the implementation of the Inspect worker command that generates a list of available symbols. This would allow for better completions.
Perhaps you've done something similar in lsp. Anyway, this looks useful to have in jsCoq for now.
> Inspect command implementation

- Makefile
- coq-js/jscoq.js
- coq-tools/mkpkg.js
- package-lock.json
- package.json
- ui-js/coq-cli.js
- ui-js/coq-manager.js
This is more of a nice-to-have and constitutes ongoing work. Since jsCoq can run on Node.js, I made a small CLI utility that allows to load packages and run vernacular commands from the shell.
The motivation for this is twofold:
* Generate symbol files for search and autocompletion functionality. (Arguably this could be done better with SerAPI.)
* Automated unit-testing that can be made part of CI.
> Node.js command-line interface (PoC)

- .travis.yml
- Makefile
- build.sh
- config.mk
- coq-addons/mathcomp.addon
- coq-js/Makefile
- coq-tools/dftlibs.ml
- coq-tools/mklibjson.ml
- docs/Build.md
This is my suggestion: separate the build of Coq from the building of the addons. It takes a long time to build all of them and some of them don't build as well as others (e.g. elpi does not build at all on macOS atm due to the ppx_deriving problem).
This PR:
* Defines separate targets `make coq` and `make addons`.
* Makes `libs` target independent of addons.
* `mklibjson` reports which packages are missing. This is more useful IMO than the previous "Addons not found" warning and in fact reveals that some of the definitions in `dftlibs.ml` are perhaps spurious.
> Separate addons

- .travis.yml
- coq-addons/mathcomp.addon
- coq-addons/odd-order.addon
- coq-external/dsp/Makefile
Tell me if this makes sense. In particular, for mathcomp, I do not see `odd_order` there, so I think we can just build with the root makefile. 
* Does it mean we can get rid of `odd_order.addon`?
* Does it mean that we can just build the official branch, or does your fork still load faster?
> Addons cleanup

- coq-jslib/dune
- coq-jslib/mklibfs.ml
- dune
So here is my devious plan: I grew weary of `Makefile.libs`, which relies on being run by Dune, but from within a `make` environment where `COQDIR` is set. It's brittle and gave me some hard time. So instead, I made `mklibfs` actually copy the files directly over to `coq-pkgs`. If you like it, we can extend it so that also the addons can be copied the same way. We can even read their `_CoqProject` files instead of listing them in `dflibs.ml`!
This PR requires rebase, this should be easy but I am waiting for the previous one.
> Mklibfs overhaul

- coq-js/dune
- coq-js/icoq.ml
- coq-js/icoq.mli
- coq-js/js_stub/marshal.js
- coq-js/jscoq_worker.ml
- coq-js/jslibmng.ml
- ui-js/coq-cli.js
This is a very preliminary attempt, it compiles the portion of the development that was evaluated so far and creates a serialized `.vo`.
I have only implemented the worker action, not the UI that goes with it. To experiment with it, run this in the devtools console:
```javascript
coq.coq.sendCommand(['Compile'])
```
The answer message is `["Got", "JsCoq.vo", Uint8Array(size)]`, where `size` is in bytes.
You can download the file by making a blob URL (this is some JavaScript voodoo):
```javascript
b = new Blob(msg[2])
URL.createObjectURL(b)
```
> `Compile` command.

- .travis.yml
- etc/toolchain-setup.sh
We add to Travis the 64 bit OSX build. For now this should be OK,
testing the 32bits one is a bit more difficult as the build is
considerably slower.
> [ci] [travis] Initial version of OSX testing.

- Makefile
- coq-addons/common.mk
- coq-addons/mathcomp.addon
- coq-addons/sf.addon
- coq-jslib/dftlibs.ml
- coq-jslib/mkpkg.js
- ui-js/coq-build.js
It is somewhat not very modular to have to list all packages, including addons, in `dftlibs.ml`.
On the other hand, our efforts towards building using jsCoq brought `coq-build.js` to a condition where it can create packages on its own, leaving aside the compilation itself, given that they have been already compiled using `coqc`. (This can be done via coq_makefile or Dune or whatever.)
Right now, this depends on `_CoqProject` to infer the logical names of the modules. But configuration *is* modular, and extensible to other formats.
I experimented by migrating `math-comp` to this new method. It builds `math-comp.json` and `math-comp.coq-pkg`, so even running `libs-pkg` is not needed.
> Proposed new, decentralized package building

- coq-addons/mathcomp.addon
- etc/patches/mathcomp-fast-load.patch
Seems to me that maintaining a patch is more sustainable than maintaining a fork of https://github.com/math-comp/math-comp.
I noticed there was an old patch file in the repo, so I updated it and made the makefile use it. It currently matches `master`. When they make a new tag for 1.9.0 I think we should set it in `mathcomp.addon` to always use that tag with the same patch so it does not break in the future.
At any rate, prior to this fix, `mathcomp` does not build due to patch mismatch.
> [bugfix] Fix mathcomp

- CHANGES.md
- Makefile
- etc/patches/timeout.patch
It seems that `Control.check_for_interrupt` is now called frequently enough, which means that now #9 can be implemented by providing an alternative timing mechanism.
This PR adds `jscoq_timeout`, overriding `unix_timeout` as the default timeout func.
> Emulation of timeout

- coq-jslib/dftlibs.ml
Since 8.8, Coq's Prelude doesn't depend on these libraries.
On a more general note, we should rework the current setup and remove
dftlibs in favor of something more principled, but OMMV.
> [libs] Don't load extraction and funind in `init`.

- CHANGES.md
- ui-css/coq-base.css
- ui-css/coq-log.css
- ui-js/jscoq-loader.js
This is actually a rather small change, but I am opening a PR for it because I removed `link.media = "screen"` that seems to have been put there purposefully.
Any reason why it should not go away?
> Printing support

- CHANGES.md
- README.md
- coq-js/icoq.ml
- coq-js/icoq.mli
- coq-js/jscoq_worker.ml
- ui-js/coq-manager.js
- ui-js/jscoq.js
I added a `coq` field in jsCoq's options where initial option values can be set.
E.g. I am using (per our previous discussion #101)
```js
...
coq: {'Default Timeout': 10}
...
```
Two things that I want to add:
* There is no documentation for the various options passed to `CoqManager`, it would be nice to have a table with the available fields and their default values, as well as sub-objects which are currently `coq` and `editor` (the latter is for setting CodeMirror options).
* I used `Goptions.set_option_value`, but obviously this only changes the global state and not the state summaries in the doc. At least the document tip should be updated.
To avoid hard questions as raised in #45, I have only implemented option setting when the worker is initialized and not later on (i.e. through the …
> Support for Coq options

- CHANGES.md
- coq-js/jser_goals.ml
- coq-js/serapi_goals.ml
- coq-js/serapi_goals.mli
- ui-css/coq-base.css
- ui-js/format-pprint.js
I looked into `proof_bullet.ml` and it seems the only "public" interface is getting a `Pp.t` when a sub-goal in complete, with a human readable description of which bullet to use next.
So I added it to `serapi_goals`.
> Focus next bullet with

- CHANGES.md
- ui-js/cm-provider.js
- ui-js/coq-manager.js
Yet another PR!
This time I wanted to rework the document held by CoqManager to facilitate asynchronous interaction with the UI and avoid different kinds of race conditions (e.g. sentence is added and then remove before the add was completed, etc.).
I think the resulting code is also somewhat cleaner, and further refactoring can be done on top of it to separate the document from CoqManager (and the DOM manipulating stuff).
> Asynchronous document model

- coq-addons/sf.addon
Still not sure this is the proper way to fix as `make addons` fails with:
```
node _build/jscoq+32bit/ui-js/coq-build.js --project /home/egallego/research/jscoq//_vendor+v8.10+32bit/lf
create-package /home/egallego/research/jscoq//_build/jscoq+32bit/coq-pkgs/LF.coq-pkg        \
--create-manifest /home/egallego/research/jscoq//_build/jscoq+32bit/coq-pkgs/LF.json
make[1]: create-package: Command not found
```
> [addons] Fix Software Foundations addon file.

- ui-css/coq-base.css
- ui-js/cm-provider.js
- ui-js/coq-manager.js
This is a small fix code-wise, but I've put it up as a PR because:
* I switched the default key for goal-hover from Alt to Ctrl. This is due to Alt being used for navigation key bindings, which causes goal view to flash.
* I noticed the landing page says that Cmd+Enter should also work for Mac. It does not, currently. It has before, I had to disable Cmd+arrows since it was interfering with Mac defaults for cursor movement, but Cmd+Enter specifically can be restored. Should it?
> Tweaking the key bindings

- CHANGES.md
- Makefile
- docs/npm-landing.html
- examples/npm-template.html
- package-lock.json
- package.json
- ui-js/coq-manager.js
- ui-js/jscoq-loader.js
- ui-js/jscoq.js
I figured that the easiest way would be to make a `tar.gz` of the distribution and then use `npm publish`.
You can try it! I published to the temporary name `@corwin.amber/jscoq`. So if you go to an empty directory and run
```
npm i @corwin.amber/jscoq
```
You will get a copy of 0.10.0 in `node_modules/@corwin.amber/jscoq`.
Some bits need to be tweaked w.r.t. paths in the directory structure created by `npm install`, so you currently if you try to open `index.html` it would fail 😞 I will play with it and fix it.
For now, I made the following decisions which we can debate on:
* I am excluding the `.vo` files and putting only the `.coq-pkg` files. Putting both is superfluous, and the `.coq-pkg` ones offer faster serving time.
* Since NPM does not support symlinks in distributed packages, …
> NPM Packaging!

- coq-js/dune
- dune
- dune-project
- dune-workspace
- dune-workspace-64
- jscoq.opam
We do require a recent toolchain [except for the compiler which is
stuck at 4.07.1 due to ppx_import]
> [jscoq] [build] Update toolchain

- CHANGES.md
- README.md
- coq-js/jslibmng.ml
- ui-js/coq-packages.js
All other libraries will require an explicit prefix in `Require`, even with the `implicit_libs` flag.
See #150.
> A policy where `implicit` only applies to Coq libs.

- CHANGES.md
- README.md
- examples/Coq86.html
- examples/Stlc.html
- examples/dft.html
- examples/equations_intro.html
- examples/gentle-intro.html
- examples/hott.html
- examples/iris.html
- examples/npm-template.html
- examples/scratchpad.html
- index.html
- package-lock.json
- package.json
- ui-css/coq-base.css
- ui-css/coq-light.css
- ui-js/cm-provider.js
- ui-js/coq-layout-classic.js
- ui-js/coq-manager.js
This has been in the works for some time and I think it's time it should be merged. It contains a bunch of things I did to be able to inject jsCoq in Software Foundations pages more cleanly. Mostly some CSS fixes so that jsCoq's styles don't interfere with ones on the page; and also the running line numbering across snippets.
The `Deprettify` class is used to convert `coqdoc` generated code blocks back to valid Coq code.
> Several CSS+JS improvements for better integration with Web pages

- CHANGES.md
- ui-js/coq-manager.js
- ui-js/coq-packages.js
Accepts dropped `.coq-pkg` files, and immediately downloads the dropped package and its dependencies.
I've tested it with the lemma overloading package (https://github.com/coq-community/lemma-overloading) suggested by @palmskog.
[lemma-overloading.zip](https://github.com/ejgallego/jscoq/files/4174149/lemma-overloading.zip)
> Package archive drop

- etc/patches/coerce-32bit.patch
Here is another patch PR that's a bit trickier: I have found that in Coq 8.11, hashconsing has become a bit more uniform and all hashes go through Hashset, which made it super easy to cap them to 30 bits. With all the hashes capped this way, marshalling with `Compat_32` works, thus making sure that the `.vo` files are indeed readable by our 32-bit jsCoq code.
WDYT?
> Compat_32 marshalling

- CHANGES.md
- README.md
- ui-js/coq-manager.js
- ui-js/coq-packages.js
This is an implementation for #156.
Some further cleanup may be required as `PackageManager` now has both `packages` and `bundles`, it would be best to have all the package information in this new `CoqPkgInfo` class.
> Multiple package paths

- CHANGES.md
- Makefile
`make coq-get-latest` will get the tip of the branch.
Still it is fairly useful to deliver jsCoq with additional patches so
we don't have to wait for official releases.
> [build] Pin to Coq 8.11.1

- CHANGES.md
- ui-css/coq-base.css
- ui-css/coq-dark.css
- ui-css/coq-light.css
- ui-js/cm-provider.js
- ui-js/coq-manager.js
I wanted to do this for a long time.
Previous behavior was to mark the whole sentence.
Now, the location reported as part of `CoqExn` is used.
> More accurate location of error indicator

- index.html
I noticed that most of the chants at the beginning of the proof are not needed for this example.
Since this is a landing page, I suggest we make it as lean as possible. So I set `options.prelude = true` and removed anything that's not necessary.
> Simplify the imports on the landing page

- .travis.yml
This is updating not to the pinned module but to the remote, which
will make CI fail.
Travis should take care of the submodules already via
```
git:
submodules: true
```
which IIANM is the default.
> [travis] Don't use incorrect git submodule call

- CHANGES.md
- docs/build.md
- etc/docker/Dockerfile
- etc/toolchain-setup.sh
- jscoq.opam
We also bump some other libraries as to reduce non-deterministic
developer switches.
This is the part of #223 that can be merged now, pending M1 support on 4.11.2
> [build] Bump required compiler version to 4.10.2

- coq-js/jscoq_interp.ml
- coq-js/jscoq_interp.mli
- coq-js/jscoq_worker.ml
This is a small refactoring that places the protocol interpreter into
its own file. This is done in preparation for the new printer.
For now I didn't complicate things much, and I have kept the
interpreter access to the `jsoo` libs, tho it would be easy to
actually make it independent by handling the interrupt code in the
worker side [by layering the protocols]
Note that in this setup we are actually architecturally very close
to just replacing our protocol by the SerAPI protocol, while I don't
think we should do that, IMHO it is important to keep the component
structure consistent about projects as SerAPI wants to reuse the
library manager for example in its jsoo version.
Another interesting TODO here would be to actually improve our worker
handling by moving some of our tricks into jsoo …
> [jscoq] Make protocol interpreter independent of worker code.

- .github/workflows/ci.yml
- etc/docker/Dockerfile
This still requires considerable work, but when ready it should
solve parts of #69 and #121.
As for now, we don't push the image to a registry yet; we ought to
decide:
- when to build the docker image [maybe only on main branches]
- where to push it
- what to include
- a standard setup for addons CI, so they pull the image and then
build and publish their own package
- how this does integrate with npm, maybe we shouldn't push the image
but just a npm package built using docker [so addons do get the
correct binaries to push to npm too]
Based on:
https://github.com/marketplace/actions/build-and-push-docker-images
> [ci] Add step to build Docker image.

- etc/docker/Dockerfile
- etc/docker/Makefile
This requires running with BuildKit if you want to build the WA branch of the build and skip JS.
Building JS should still work with older Docker.
> Dual-branch Dockerfile

- coq-js/jscoq_interp.ml
- coq-js/jscoq_proto.ml
- ui-js/coq-manager.js
- ui-js/headless.ts
- ui-js/ide-project.js
That's better w.r.t. future, we also add a msg field which is the
rendered plain string, useful when debugging early stages or low-level
as the CoqPP is hard to read and in that setup, we may not be able to
to access the pp printer yet.
Backported from the 8.14 branch, as it is and independent change that should be reviewed separatedly.
> [cleanup] Reify CoqExn data into a Json object

- CHANGES.md
- etc/docker/Dockerfile
- etc/docker/Makefile
- etc/docker/gosu-entrypoint.sh
- examples/sdk-demo/bin/coqc
I wanted to work on the SDK setup. It's coming up nicely. One serious obstacle was the Docker images only working on x64, which meant Mac users (myself included) would not be able to use the SDK. This is rectified in this PR.
Namely:
* A `WORDSIZE` argument is added to the Dockerfile. It is 32 by default.
* The Makefile in the same directory sets `WORDSIZE=64` when building on a Mac. This is because Macs lack 32-bit backward compat as was discussed a long while ago.
* When `WORDSIZE` = 64, the build process would not add the `i386` architecture and `multilib` packages, and would install mainstream OCaml instead of the 32-bit variant.
* The switch will be called `jscoq+64bit` and `toolchain-setup.sh --64` will be invoked.
That's about it. Based on the `coerce-32bit` patch, the builds …
> Docker multiarch

- .gitmodules
- dune
- jscoq.opam
We move vendored things to `vendor` and let dune know about it.
We bump serapi dep to the head of the v8.16 branch.
We also adjust build deps a bit better, in particular to avoid Dune
3.4 which is buggy for us.
Beware this will require `git submodule update` on the work tree.
> [build] Adjust vendoring paths + deps

- ui-js/coq-layout-classic.js
- ui-js/coq-manager.js
- ui-js/coq-packages.js
- ui-js/headless.ts
- ui-js/index.js
- ui-js/jscoq-worker-interface.js
Instead of using a JsCoq global, we pass the needed parameters to the
constructors so the components types are more functional.
The access to the global was mostly used to determine the backend, but
IMHO this is morally wrong as nothing should preclude a manager
creating N worker objects with different backends.
Moreover, most of the backend case analysis should go away once we
improve backend handling.
This is also a step towards frontend / backend separation.
Next step is indeed to isolate the backend options in their own
interface.
> [js] [refactor] Remove use of JsCoq global in components.

- dune
- jscoq.opam
- webpack.config.js
This fixes the directory target rule problem.
Thanks to Rudi Grinberg!
Dune 3.5.0 is not released yet, but it is expected before the end of the week.
> [build] Bump Dune to >= 3.5.0

- etc/docker/Dockerfile
f67e5e27 modifies the dist rule in the Makefile, so that the Dockerfile no longer needs to do anything more than `make dist`.
> Dockerfile: fix build since f67e5e27

- CHANGES.md
- docs/build.md
- dune
- examples/scratchpad.html
- frontend/classic/js/addon/collab/gist.js
- frontend/classic/js/addon/collab/index.ts
- frontend/classic/js/cm-provider.ts
- frontend/classic/js/coq-manager.js
- frontend/classic/js/coq-packages.ts
- frontend/cli/build/workspace.ts
- package.json
> Add Gist sharing support

- CHANGES.md
- etc/docker/Dockerfile
We configure the build in 3 stages:
- system deps of Coq (apt, wasi)
- opam deps of Coq and jsCoq (ocaml-level)
- jscoq itself
This should speed the build up, improve logs, and is IMHO a bit more principled and in-sync with the way caching works in CI these days.
We use a naming scheme for the stages `coq-base`, `jscoq-base`.
> [docker] Streamline Docker stages

- CHANGES.md
- Makefile
- etc/docker/Makefile
- etc/serve.json
Note this required a change from npm `http-server` to more modern `serve` package.
> [build] `make serve` now properly sets headers so `SharedArrayBuffer` works

- CHANGES.md
- backend/common/jscoq_interp.ml
- backend/jsoo/dune
- backend/jsoo/js_stub/unix.js
- backend/jsoo/jscoq_worker.ml
- backend/jsoo/jslibmng.ml
- examples/sdk-demo/dune-project
- frontend/cli/build/project.ts
- jscoq.opam
Note that we now link `js_of_ocaml-compiler.dynlink` which pulls
`js_of_ocaml-compiler` and `compiler-libs.bytecomp`.
> [build] [js] Update to jsoo 5.9.1 from 4.0.0

- .github/workflows/ci.yml
- Makefile
- dune-workspace.local
- etc/toolchain-setup.sh
This enables the dune / opam cache, which makes CI much faster.
We also incorporate some other improvements from coq-lsp CI.
> [ci] Use setup OCaml for OPAM setup 

- CHANGES.md
CM5 TeX-input addon does understand backlash using physical keyboard codes. This made jsCoq hard to use in non US keyboards layouts, like French or Spanish.
Fixed upstream in
https://github.com/ejgallego/CodeMirror-TeX-input/pull/3 by @helguo
> [cm5] Fix longstanding issue with CodeMirror completion

- .github/workflows/ci.yml
- CHANGES.md
- CONTRIBUTING.md
- README.md
- docs/build.md
- etc/docker/Dockerfile
- etc/toolchain-setup.sh
`toolchain-setup.sh` failed to create an `opam switch` (for example `jscoq+32bit`) because no argument is given.
The switch name is built correctly now.
> [build] fix argument issue in toolchain-setup.sh

- jscoq.opam
This was already found by @helguo, but already fixed upstream.
We just avoid the problematic version.
cc: https://github.com/ocsigen/lwt/issues/1072
> [opam] Avoid lwt 5.9.2
