package-lock.json
package.json

[npm] Update bootstrap dependency to fix security issue.

---

.travis.yml
Makefile
coq-external/dsp/Makefile
coq-js/dune
coq-js/jscoq_worker.ml
coq-jslib/mklibfs.ml
dune
etc/patches/avoid-vm.patch
etc/patches/trampoline.patch
jscoq.opam
ui-js/coq-cli.js

I am aware that some of the paths are in makefiles and these are gradually being phased out. But at least for now let them be consistent 😉 
I have another more radical PR coming up.

Some cleanup in paths

---

CHANGES.md
coq-js/js_stub/coq_vm.js
coq-js/js_stub/str.js
coq-js/js_stub/unix.js
coq-js/jslibmng.ml
jscoq.opam

There is some extra deprecation that we need to take care of.
Pending on #75 tho.

[coq] Update to JSOO 3.4.0

---

Makefile
etc/patches/lazy-noinline.patch

I tried OCaml 4.06.1, but this did not solve the problem. So I suggest we include this patch in 0.9.

[bugfix] Backported `Lazy.force` patch.

---

CHANGES.md
README.md
coq-js/jscoq_worker.ml
etc/notes/announce-0.9.md
package-lock.json
package.json

We tag the version as 0.9.3 due to prior versioning by Shachar. Closes #42

[general] Release 0.9 !

---

docs/build.md

@corwin-of-amber let me know what more we should add to close #35

[doc] Tweak to build notes, closes #35

---

.travis.yml

* Select `language: node_js` and Node.js 8.x to enable newer features (async/await).
* Reorganize the build matrix and use the Homebrew addon.

Fixing Travis

---

CODE_OF_CONDUCT.md

This is taken from SerAPI; I'm not expert on CoCs but the intentions
are IMHO clear.

[community] Add a Code of Conduct.

---

README.md

Addresses #91.
I noticed that Ctrl-Alt-O does not work on Mac in #118. Will fix it there.

Update README with keys and open/save.

---

CHANGES.md
README.md
ui-css/coq-base.css
ui-js/coq-layout-classic.js

I played around with the layout a bit this evening.
It looks and behaves almost like the previous layout (that uses "fixed" and padding), but fixes some issues such as the vertical scrollbar appearing to the right of the panel.
Also a max-width of 37em was set for the panel.
(it's a bit arbitrary, but the `#document` is set to 51em, so I said meh)

Alternative layout definition with flex

---

CHANGES.md
README.md
coq-js/jscoq_version.ml
coq-js/jscoq_worker.ml
package.json

Notes:
- added file with version, will be auto-generated in the future
- updated copyright headers in main file
Closes #47

[jscoq] Release 0.10.1

---

etc/patches/trampoline.patch

To avoid some stack overflows in Search.

Trampolining code in constr_matching as well.

---

Makefile
etc/patches/cps.patch

Solved by a CPS version of `List.fold_right`, local patch to Coq.
Fixes #161.

Stack overflow in Require

---

coq-js/icoq.ml
coq-js/jscoq_proto.ml
coq-js/jscoq_worker.ml
coq-js/jslibmng.ml
dune
etc/patches/timeout.patch

This should make things easier in case we want to use the dev profile.

[build] Fix a few warnings, adjust flags.

---

project-builder.html
ui-css/components/file-list.css
ui-css/project.css
ui-js/components/file-list.js
ui-js/components/problem-list.js
ui-js/coq-build.js
ui-js/coq-cli.js
ui-js/coq-packages.js
ui-js/jscoq.js

The builder went stale and stopped working following changes to jsCoq's core functionality.
This feature has never matured enough to be used, but I'm preparing to refactor it quite substantially.

Fix project-builder

---

CONTRIBUTING.md

For a while I've been wanting to make clear that the development here
should not turn into something too bureaucratic and we should not be
afraid at all of committing stuff to master. I guess just before the
move to an organization this update should happen.
I dunno about the wording tho, suggestions welcome.

[contributing] Some notes about review / merge

---

dune

[build] Fix missing dependency on addons install directory.

---

Makefile
coq-addons/extlib.addon
coq-addons/mathcomp.addon
coq-addons/quickchick.addon
coq-addons/simpleio.addon
coq-jslib/dftlibs.ml
dune
index.html

Seems to work OK, more tests are needed.
We are at a point tho where we could consider supporting opam packages maybe?

[addons] Add QuickChick

---

dune

This is a workaround for #171 until we have something better.

[build] Always rebuild coq-pkgs

---

README.md
docs/developing.md
docs/embedding.md
docs/papers.md

I have done a quick pass and tried to tidy the readme up a bit.
Please don't hesitate to further refine.

[readme] Update for 8.11 and recent changes.

---

CHANGES.md
etc/notes/announce-0.11.md
etc/notes/todo.md

[changes] 0.11 release announcement

---

README.md

[readme] mailing list -> Zulip

---

ui-js/cm-provider.js
ui-js/coq-manager.js

I have implemented this feature in waCoq because it is needed to reasonably support Software Foundations.
Basically, they have some of the Coq code wrapped in special comments `(* HIDEFROMHTML *) ... (* /HIDEFROMHTML *)` and then the corresponding element gets hidden. Some of the code treated thus is needed to correctly execute the development, and is redacted from the HTML for readability (sometimes it's importing stuff from previous chapters, setting some options, etc.).
So I incorporated a solution where this code is wrapped in a CodeMirror that is itself hidden. This is well, but then it gets awkward if the user navigates forward or backward and ends up in a hidden portion of the document. Hence I reprogrammed the `goNext` and `goPrev` logic to "step over" these blocks, so that you …

Allowing hidden snippets in documents

---

dune
ui-js/dune

This has some minor advantages, including dune handling of arguments.

[build] Don't use bash to run simple commands.

---

.travis.yml

Yeah, planning to move to GitHub Actions instead of Travis CI, but haven't figured out who's who yet.
So trying to at least have a save Travis build in the meantime.

Add missing deps for Linux build in Travis

---

CHANGES.md
coq-js/js_stub/unix.js
docs/build.md
etc/consume-addons
etc/docker/Dockerfile
etc/toolchain-setup.sh
jscoq.opam

This needs testing from @corwin-of-amber

[build] Bump required compiler version to 4.12.0

---

examples/sqrt2.v

Rebased PR for 8.15 as requested by @corwin-of-amber in #253.

add proof of irrationality of sqrt of 2 as example for 8.15

---

.github/workflows/ci.yml
Makefile
docs/build.md

[ci] Update for newer toolchain.

---

coq-js/code_info.ml
coq-js/code_info.mli
coq-js/icoq.ml
coq-js/icoq.mli
coq-js/jscoq_interp.ml
coq-js/jscoq_proto.ml

This code is fully independent of jsCoq and should be shared by all
the UI libs.

[refactoring] Put code info tools in their own file.

---

coq-js/code_info.ml
coq-js/code_info.mli
coq-js/jscoq_interp.ml

We don't need to expose the filtering semantics.

[inspect] Refactor the API a bit more.

---

ui-js/coq-manager.js
ui-js/future.js
ui-js/headless.ts
ui-js/jscoq-worker-interface.js

This is in preparation towards a more generic Notification/Request
model for the servers.

[js] Factor out future to its own file / interface.

---

.github/workflows/ci.yml
Makefile
examples/playful.html
package-lock.json
tests/main.js

Still, both don't fully work, needs more research as to witness what's
broken.

[misc] Misc fixes to playful and the test runner.

---

jscoq.opam
package-lock.json

[deps] Bump some deps (opam and npm problems)

---

.github/workflows/ci.yml

Another step towards restoring CI.

[ci] Don't double-build pull requests hosted in main repos.

---

.github/workflows/ci.yml
CHANGES.md
Makefile
backend/jsoo/jscoq_worker.ml
dune

We will use this for frontend testing later on, it is also very useful to deploy.

[ci] Build jsCoq artifact
